apiVersion: v1
kind: Service
metadata:
  name: demo-app-welcome-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-app-welcome
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-welcome-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-welcome
  template:
    metadata:
      labels:
        app: demo-app-welcome
    spec:
      containers:
        - name: demo-app-container
          image: registry.eecicd.com:50000/welcome_comp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
---
 apiVersion: autoscaling/v2
 kind: HorizontalPodAutoscaler
 metadata:
   name: demo-app-welcome-hpa
   namespace: default
 spec:
   behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
   maxReplicas: 10
   minReplicas: 1
   scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: demo-app-welcome-deployment
   metrics: 
   - type: Resource
     resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


    