apiVersion: v1
kind: Service
metadata:
  name: demo-app-date-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-app-date
  ports:
    - port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-date-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-date
  template:
    metadata:
      labels:
        app: demo-app-date
    spec:
      containers:
        - name: demo-app-date
          image: registry.eecicd.com:50000/date_comp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP